### PR TITLE
change the vehicle Endpoint

### PR DESCRIPTION
**Pull request by rliegmann**
The VW Group has changed one of its endpoints.
The vehicles endpoint has been adjusted.

Tested with access data from:

- Seat Leon 
- Seat Electric Mii

### CODE REVIEW

**Comment by ronald-den-otter** [comment]
Tested it on Cupra Formentor by patching the commit above and it worked :-)

**Comment by Bewo** [comment]
Great job! - I also can confirm: Works fine again with an Cupra Leon Sportstourer eHybrid!
Thanks for all your work!

**Comment by ronald-den-otter** [comment]
> Tested it on Cupra Formentor by patching the commit above and it worked :-)

Besides this message:
DEBUG:seatconnect.connection:HTTP GET "https://customer-profile.apps.emea.vwapps.io/v2/customers/7ecfb513-23c7-45ef-9598-a1cb4bceea65/realCarData"
DEBUG:seatconnect.connection:Got non HTTP related error: Cannot connect to host customer-profile.apps.emea.vwapps.io:443 ssl:default [Name or service not known]
INFO:seatconnect.connection:Unhandled error while trying to fetch realcar data

probably deprecated with changed vehice endpoint

**Comment by rliegmann** [comment]
@ronald-den-otter 
I get this error too. Should be something with "Get car information from customer profile, VIN, nickname, etc.""" Unfortunately I don't know exactly what that is. Has the endpoint changed?
The important dates are coming. :-) 
I would ignore it for now.

**Comment by ronald-den-otter** [comment]
> 
See this commit
https://github.com/Farfar/seatconnect/pull/7/commits/2cc6be04fbd8b5f21cca915e47bad0d97d544dc2
But besides the error it doesnt seem to hurt it.

**Comment by Farfar** [comment]
Changing the URLs into "mal-3a" statically is probably a bad idea. The other brands have had some way of fetching the "home region" or API base URL used for fetching data. My guess is that Seat/Cupra now also use these newer domains but without knowing if the app also makes use of a home region URL detection I can't do much else than merging this PR and we'll hope for the best.
The proper way to do this would be investigating the first startup for the app and investigate if any homeregion url is used.

**Comment by Farfar** [comment]
Thanks @rliegmann for providing the updated endpoints

**Pull request merged**
